server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo
#          username: shawn
#          password: 000000
      label: master
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8889/erueka/

